baseURL: 'https://www.tribalthirst.com/'
languageCode: 'en-us'
title: 'Tribal Thirst'
subtitle: 'Loving, Learning, Leading, Listening'
author:
  name: Mark Kola - TribalThirst
copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0
  International License.
languageCode: en-us
enableInlineShortcodes: true
googleAnalytics: "G-1T8WZQSYDB"
disqusShortname: tribalthirst
menu:
  main:
    - identifier: about
      name: About
      url: /pages/about-tribalthirst
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 3
    - indentifier: posts
      name: Posts
      url: /posts/
      weight: 4
theme: 'tribalthirst'


