baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Tribal Thirst'
subtitle: 'Loving, Learning, Leading, Listening'
theme: 'tribalthirst'
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 2
    - indentifier: posts
      name: Posts
      url: /posts/
      weight: 1


