baseURL: 'https://www.tribalthirst.com/'
languageCode: 'en-us'
title: 'Tribal Thirst'
subtitle: 'Loving, Learning, Leading, Listening'
enableInlineShortcodes: true
googleAnalytics: "G-1T8WZQSYDB"
menu:
  main:
    - identifier: about
      name: About
      url: /pages/about-tribalthirst
      weight: 4
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 2
    - indentifier: posts
      name: Posts
      url: /posts/
      weight: 1
theme: 'tribalthirst'


