baseURL: 'https://tribalthirst.com/'
languageCode: 'en-us'
title: 'Tribal Thirst'
theme: 'anatole'
enableInlineShortcodes: true
enableRobotsTXT: true
googleAnalytics: "G-1T8WZQSYDB"
preserveTaxonomyNames: true
params:
  subtitle: 'Loving, Learning, Leading, Listening'
  author:
    name: Mark Kola - TribalThirst
  copyright: 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License. Theme: [Anatole](https://themes.gohugo.io/themes/anatole/).'
  socialIcons:
    - icon: fa-brands fa-linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/tribalthirst
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: -10
    
    
    - identifier: about
      name: About
      url: /pages/about-tribalthirst
      weight: 5
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 1


