baseURL: 'https://tribalthirst.com/'
languageCode: 'en-us'
title: 'Tribal Thirst'
theme: 'tribalthirst'
enableInlineShortcodes: true
enableRobotsTXT: true
googleAnalytics: "G-1T8WZQSYDB"
preserveTaxonomyNames: true
params:
  subtitle: 'Loving, Learning, Leading, Listening'
author:
  name: Mark Kola - TribalThirst
copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0
  International License.
menu:
  main:
    - identifier: connect
      name: Connect
      url: /pages/subscribe
      weight: 5
    - identifier: about
      name: About
      url: /pages/about-tribalthirst
      weight: 5
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 1
    - identifier: micro
      url: /micro/
      name: Micro
      weight: 4


