
name: Azure Static Web Apps API CI/CD

on:
  workflow_dispatch:

jobs:
  build_and_deploy_api:
    runs-on: ubuntu-latest
    name: Build and Deploy API (.NET 8 Isolated)
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./api/api.csproj

      - name: Build API
        run: dotnet build ./api/api.csproj --configuration Release --no-restore

      - name: Run Unit Tests (exclude Integration)
        run: dotnet test ./api.Tests/api.Tests.csproj --filter TestCategory!=Integration

      - name: Publish API
        run: dotnet publish ./api/api.csproj --configuration Release --output ./api-publish --no-build

      - name: Deploy API to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_SAND_03F957810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "api-placeholder" # Minimal static site placeholder for API-only deployment
          api_location: "api-publish"
          output_location: "" # No static site output
